### ISSUE TITLE
Not able to load model

### ISSUE THREAD

**Issue by hemalgadhiya** [anujshah1003/convolution-layer-visualization-VGG-16#3]
I am getting the following error when i try to load H5 file

OSError: Unable to open file (unable to open file: name = '('G:/8th sem/review_1/demo_1.h5', '')', errno = 22, error message = 'Invalid argument', flags = 0, o_flags = 0)

**Comment by s1011448** [comment]
I am getting the same error when loading my model.

**Comment by Biinzy** [comment]
I am getting the same error, have you find a solution?

**Comment by Dhananjay1646** [comment]
Me too.....  getting the same error when loading my model

-----------Loading the Model-----------------------
Traceback (most recent call last):
  File "vgg16_intermediate_layer_visualization_gui.py", line 54, in browseModel
    self.model=load_model(self.fname)
  File "C:\Users\HP\Anaconda3\envs\env1\lib\site-packages\keras\engine\saving.py", line 249, in load_model
    f = h5py.File(filepath, mode='r')
  File "C:\Users\HP\Anaconda3\envs\env1\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\HP\Anaconda3\envs\env1\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '('convolution-layer-visualization-VGG-16-master/VGG-16-visualization/VGG16.hdf5', 'All Files (*)')', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by Dhananjay1646** [comment]
Change;
`self.fname = str(self.filePath)`  line no. 46 to 
`self.fname = str(self.filePath[0])`
